spring:
  application:
      name: shopapp
  datasource:
    url: 'jdbc:mysql://localhost:3306/db_shop_app?createDatabaseIfNotExist=true'
    username: root
    password: 123456
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: false
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0

file:
  upload-dir: 'uploads\'

server:
  port: 8080
  servlet:
    context-path: /api/v1
    
jwt:
  secret: '3q2+7w==e3r5t6y7u8i9o0p1a2s3d4f5g6h7j8k9l0z1x2c3v4b5n6m'
  expiration: 86400000