ALTER TABLE products
ADD COLUMN stock BIGINT NOT NULL DEFAULT 100;

ALTER TABLE orders
MODIFY COLUMN status VARCHAR(255) DEFAULT 'PENDING';

UPDATE orders
SET status = 'CANCELLED'
WHERE status = 'CANCELED';
